[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
startCommand = "uvicorn app:app --host 0.0.0.0 --port $PORT --workers 1"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
